name: bacabuku
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  avatar_brick:
    git:
      url: https://github.com/congson99/avatar_brick.git
  animation_search_bar: ^0.0.10
  flutter_animate: ^4.2.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: playfair
      fonts:
        - asset: fonts/playfair.ttf
    - family: amiri
      fonts:
        - asset: fonts/amiri-bold.ttf
        - asset: fonts/amiri-regular.ttf
